### ISSUE TITLE
Not working on Libresprite

### ISSUE THREAD

**Issue by enderprism** [Abbabon/aseprite-dracula-theme#4]
I am on EndeavourOS and I installed Libresprite with Flatpak.
To install the theme, I extracted the theme folder to Libresprite's skin folder and the palette to the corresponding palette folder.
The app has already been restarted, and the theme applied (I renamed theme.xml to skin.xml for Libresprite to not crash at startup) but it still uses the default theme.
Note that I had to copy Libresprite's font.png, minifont.png and palette.png to the dracula theme folder because without them, Libresprite would crash upon starting up.
![Libresprite screenshot](https://user-images.githubusercontent.com/76617157/201471192-833f31cb-6c3f-4cab-ab8b-38bb6cf66a3b.png)

**Comment by Abbabon** [comment]
As Libersprite is a fork of Aseprite from 2016, I see little sense in maintaining support for it in the same repo as the Aseprite theme due to Entropy and expect the changes to not be compatible.. However, I encourage you (or any brave, contributing soul) to fork this repo and make the necessary changes :)

I am closing this issue.

Had I had more free time, I would have gladly done it myself.
